# Generated by Django 5.0 on 2024-03-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('education', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('notes', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family_tree.family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('aunt_uncle', 'Aunt/Uncle'), ('niece_nephew', 'Niece/Nephew'), ('cousin', 'Cousin')], max_length=12)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='family_tree.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='family_tree.person')),
            ],
            options={
                'unique_together': {('from_person', 'to_person', 'relationship_type')},
            },
        ),
    ]
